-- Phase 2 — Migration 005: Seed initial data
-- Run with: psql -f supabase/migrations/005_seed.sql
-- This seeds the database with the SAME data that ships in
-- assets/js/store-data.js DEFAULT_DATA. Existing live localStorage data is
-- NEVER touched by this script. The seed is idempotent (uses on conflict
-- do nothing) so it is safe to re-run.
--
-- WARNING: This seed contains HISTORICAL demo identity data ("Anwar Store").
-- Migration 008 (008_update_store_identity.sql) MUST be run after this to
-- update the store identity to "Ahmad Kamal". Do NOT apply this migration
-- to a fresh database without also applying migration 008.
--
-- IMPORTANT: Monetary values are written as exact decimal strings to preserve
-- 0.60, 1.50, 3.00 etc. without floating-point artefacts. The order number
-- is generated by public.next_order_number() on the server.

-- =========================================================
-- 0. Make the seed run as a regular (non-admin) user safely
-- =========================================================
-- This is a one-off seed intended to be executed by a Supabase migration
-- job (which runs as the database owner). It does NOT require an admin user.

-- =========================================================
-- 1. settings (singleton row)
-- =========================================================
insert into public.settings (
  id, store_name, store_name_en, tagline,
  primary_color, accent_color,
  contact_email, contact_phone, whatsapp, address,
  currency, currency_code,
  facebook, instagram, twitter, tiktok, snapchat, youtube,
  free_shipping_threshold, default_shipping_cost,
  hero_slides, announcement, homepage_sections, navigation,
  floating_whatsapp, footer, invoice
) values (
  1,
  'متجر أنور', 'Anwar Store', 'أناقة بلا حدود',
  '#14b8a6', '#1a1a1a',
  'info@anwar-store.com', '+962 79 000 0000', '962790000000', 'عمّان، المملكة الأردنية الهاشمية',
  'د.أ', 'JOD',
  'https://facebook.com/anwar', 'https://instagram.com/anwar', '', '', '', '',
  50, 0,
  '[
    {"id":"s1","title":"مجموعة الموسم الجديدة","subtitle":"اكتشف أحدث صيحات الموضة العالمية بأسعار لا تُقاوم","cta":"تسوق الآن","link":"#shop","image":"","active":true,"order":1},
    {"id":"s2","title":"خصومات تصل إلى 50%","subtitle":"عروض حصرية على تشكيلة مختارة من المنتجات الفاخرة","cta":"استكشف العروض","link":"#shop","image":"","active":true,"order":2},
    {"id":"s3","title":"توصيل سريع لجميع المحافظات","subtitle":"اطلب الآن واحصل على طلبك خلال 24-48 ساعة في جميع أنحاء الأردن","cta":"تسوق حسب الفئة","link":"#shop","image":"","active":true,"order":3}
  ]'::jsonb,
  '{"enabled":true,"image":"","title":"شحن مجاني للطلبات فوق 50 دينار","text":"استفد من عرض الشحن المجاني على جميع الطلبات فوق 50 دينار أردني في جميع محافظات المملكة","cta":"تسوق الآن","link":"#shop","bgColor":"#14b8a6"}'::jsonb,
  '{"featured":{"enabled":true,"title":"منتجات مميزة","subtitle":"مختارة خصيصاً لك","productIds":[]},"newArrivals":{"enabled":true,"title":"وصل حديثًا","subtitle":"أحدث المنتجات في متجرنا","productIds":[]},"onSale":{"enabled":true,"title":"عروض وتخفيضات","subtitle":"وفر أكثر مع تخفيضاتنا الحصرية","productIds":[]}}'::jsonb,
  '[
    {"id":"n1","label":"الرئيسية","type":"route","value":"home","order":1,"active":true},
    {"id":"n2","label":"العروض","type":"route","value":"offers","order":2,"active":true},
    {"id":"n3","label":"وصل حديثًا","type":"route","value":"new","order":3,"active":true},
    {"id":"n4","label":"جميع المنتجات","type":"route","value":"shop","order":4,"active":true},
    {"id":"n5","label":"طلباتي","type":"route","value":"myorders","order":5,"active":true}
  ]'::jsonb,
  '{"enabled":true,"message":"مرحباً، أرغب بالاستفسار عن منتجاتكم"}'::jsonb,
  '{"aboutText":"متجر أنور وجهتك المثالية للأزياء العصرية والأنيقة. نقدم لك تشكيلة واسعة من الملابس والإكسسوارات بأعلى جودة وأفضل الأسعار مع خدمة توصيل سريعة لجميع محافظات المملكة الأردنية الهاشمية.","showSocial":true,"showPhone":true,"showWhatsapp":true,"showAddress":true,"copyright":""}'::jsonb,
  '{"normal":{"headerText":"","footerText":"شكراً لتعاملكم معنا","extraText":"","colors":{"text":"#1a1a1a","heading":"#0d9488","border":"#e8e3d8","total":"#6b4423"}},"thermal":{"enabled":false,"paperSize":"80mm","qrUrl":"","headerText":"","footerText":"شكراً لزيارتكم","extraText":"","colors":{"text":"#000000","heading":"#000000","border":"#000000","total":"#000000"}}}'::jsonb
)
on conflict (id) do nothing;

-- =========================================================
-- 2. categories
-- =========================================================
insert into public.categories (legacy_id, name, icon, parent_id, display_order) values
  ('c1', 'ملابس رجالية', '👔', null, 1),
  ('c2', 'ملابس نسائية', '👗', null, 2),
  ('c3', 'أحذية', '👟', null, 3),
  ('c4', 'إكسسوارات', '⌚', null, 4),
  ('c5', 'عطور', '🌸', null, 5),
  ('c6', 'حقائب', '👜', null, 6)
on conflict (legacy_id) do nothing;

-- Subcategories: parent_id resolved by a CTE to keep this insert order-independent.
with parents as (
  select legacy_id, id from public.categories where legacy_id in ('c1','c2')
)
insert into public.categories (legacy_id, name, icon, parent_id, display_order)
select 'c1-1', 'قمصان', '👕', (select id from parents where legacy_id = 'c1'), 1
where not exists (select 1 from public.categories where legacy_id = 'c1-1');

with parents as (
  select legacy_id, id from public.categories where legacy_id in ('c1','c2')
)
insert into public.categories (legacy_id, name, icon, parent_id, display_order)
select 'c1-2', 'بناطيل', '👖', (select id from parents where legacy_id = 'c1'), 2
where not exists (select 1 from public.categories where legacy_id = 'c1-2');

with parents as (
  select legacy_id, id from public.categories where legacy_id in ('c1','c2')
)
insert into public.categories (legacy_id, name, icon, parent_id, display_order)
select 'c2-1', 'فساتين', '👗', (select id from parents where legacy_id = 'c2'), 1
where not exists (select 1 from public.categories where legacy_id = 'c2-1');

with parents as (
  select legacy_id, id from public.categories where legacy_id in ('c1','c2')
)
insert into public.categories (legacy_id, name, icon, parent_id, display_order)
select 'c2-2', 'عبايات', '🥻', (select id from parents where legacy_id = 'c2'), 2
where not exists (select 1 from public.categories where legacy_id = 'c2-2');

-- =========================================================
-- 3. products
-- =========================================================
-- All monetary values are written as exact decimal strings so 180.00, 850.00,
-- 420.00 etc. are preserved without any floating-point conversion.

with cat as (select legacy_id, id from public.categories)
insert into public.products (
  legacy_id, sku, name, short_description, description,
  category_id, price, old_price, stock, images,
  featured, is_new, on_sale, active, rating, reviews, display_order
) values (
  'p1', 'SH-001', 'قميص كلاسيكي أزرق', 'قميص قطني أنيق',
  'قميص رجالي كلاسيكي بقماش قطني عالي الجودة، مناسب للمناسبات الرسمية وغير الرسمية.',
  (select id from cat where legacy_id = 'c1-1'), 180.00, 250.00, 24,
  array['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600'],
  true, false, true, true, 4.6, 32, 0
) on conflict (legacy_id) do nothing;

with cat as (select legacy_id, id from public.categories)
insert into public.products (legacy_id, sku, name, short_description, description, category_id, price, old_price, stock, images, featured, is_new, on_sale, active, rating, reviews, display_order) values
  ('p2', 'DR-002', 'فستان سهرة أسود فاخر', 'فستان فاخر للسهرات',
   'فستان سهرة أنيق بقصة حورية البحر، مزين بتطريز يدوي فاخر، مناسب للمناسبات الخاصة.',
   (select id from cat where legacy_id = 'c2-1'), 850.00, 1200.00, 12,
   array['https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600'],
   true, true, true, true, 4.9, 58, 0)
on conflict (legacy_id) do nothing;

with cat as (select legacy_id, id from public.categories)
insert into public.products (legacy_id, sku, name, short_description, description, category_id, price, old_price, stock, images, featured, is_new, on_sale, active, rating, reviews, display_order) values
  ('p3', 'SH-003', 'حذاء رياضي أبيض عصري', 'حذاء رياضي عصري',
   'حذاء رياضي عصري مريح للاستخدام اليومي، خفيف الوزن بتصميم مبتكر.',
   (select id from cat where legacy_id = 'c3'), 420.00, 0, 18,
   array['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600'],
   true, true, false, true, 4.7, 89, 0)
on conflict (legacy_id) do nothing;

with cat as (select legacy_id, id from public.categories)
insert into public.products (legacy_id, sku, name, short_description, description, category_id, price, old_price, stock, images, featured, is_new, on_sale, active, rating, reviews, display_order) values
  ('p4', 'AC-004', 'ساعة يد فاخرة ذهبية', 'ساعة فاخرة بإطار ذهبي',
   'ساعة يد فاخرة بإطار ذهبي وسوار جلدي إيطالي، مقاومة للماء حتى 50 متر.',
   (select id from cat where legacy_id = 'c4'), 1500.00, 2200.00, 6,
   array['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600'],
   true, false, true, true, 4.8, 41, 0)
on conflict (legacy_id) do nothing;

with cat as (select legacy_id, id from public.categories)
insert into public.products (legacy_id, sku, name, short_description, description, category_id, price, old_price, stock, images, featured, is_new, on_sale, active, rating, reviews, display_order) values
  ('p5', 'PR-005', 'عطر شرقي مميز', 'عطر شرقي فاخر 100مل',
   'عطر شرقي فاخر بمزيج العود والورد والمسك، عبوة 100 مل.',
   (select id from cat where legacy_id = 'c5'), 320.00, 0, 30,
   array['https://images.unsplash.com/photo-1541643600914-78b084683601?w=600'],
   false, true, false, true, 4.9, 67, 0)
on conflict (legacy_id) do nothing;

with cat as (select legacy_id, id from public.categories)
insert into public.products (legacy_id, sku, name, short_description, description, category_id, price, old_price, stock, images, featured, is_new, on_sale, active, rating, reviews, display_order) values
  ('p6', 'BG-006', 'حقيبة يد جلدية بنية', 'حقيبة جلد طبيعي',
   'حقيبة يد نسائية من الجلد الطبيعي الإيطالي، تصميم عصري وأنيق.',
   (select id from cat where legacy_id = 'c6'), 680.00, 950.00, 9,
   array['https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600'],
   true, false, true, true, 4.5, 23, 0)
on conflict (legacy_id) do nothing;

with cat as (select legacy_id, id from public.categories)
insert into public.products (legacy_id, sku, name, short_description, description, category_id, price, old_price, stock, images, featured, is_new, on_sale, active, rating, reviews, display_order) values
  ('p7', 'PN-007', 'بنطلون جينز كلاسيكي', 'جينز كلاسيكي مريح',
   'بنطلون جينز كلاسيكي بقصة مستقيمة، خامة قطنية مرنة مريحة.',
   (select id from cat where legacy_id = 'c1-2'), 220.00, 0, 35,
   array['https://images.unsplash.com/photo-1542272604-787c3835535d?w=600'],
   false, false, false, true, 4.4, 51, 0)
on conflict (legacy_id) do nothing;

with cat as (select legacy_id, id from public.categories)
insert into public.products (legacy_id, sku, name, short_description, description, category_id, price, old_price, stock, images, featured, is_new, on_sale, active, rating, reviews, display_order) values
  ('p8', 'AB-008', 'عباية سوداء مطرزة', 'عباية بتطريز يدوي',
   'عباية سوداء فاخرة بتطريز يدوي على الأكمام والأطراف، قماش كريب ممتاز.',
   (select id from cat where legacy_id = 'c2-2'), 590.00, 0, 16,
   array['https://images.unsplash.com/photo-1590548784585-643d2b9c2928?w=600'],
   true, true, false, true, 4.8, 78, 0)
on conflict (legacy_id) do nothing;

with cat as (select legacy_id, id from public.categories)
insert into public.products (legacy_id, sku, name, short_description, description, category_id, price, old_price, stock, images, featured, is_new, on_sale, active, rating, reviews, display_order) values
  ('p9', 'AC-009', 'نظارة شمسية أنيقة', 'نظارة بعدسات مستقطبة',
   'نظارة شمسية بإطار معدني وعدسات مستقطبة، حماية كاملة من الأشعة فوق البنفسجية.',
   (select id from cat where legacy_id = 'c4'), 280.00, 400.00, 22,
   array['https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600'],
   false, false, true, true, 4.3, 18, 0)
on conflict (legacy_id) do nothing;

with cat as (select legacy_id, id from public.categories)
insert into public.products (legacy_id, sku, name, short_description, description, category_id, price, old_price, stock, images, featured, is_new, on_sale, active, rating, reviews, display_order) values
  ('p10', 'JK-010', 'جاكيت جلد طبيعي', 'جاكيت جلد طبيعي',
   'جاكيت رجالي من الجلد الطبيعي الأصلي، تصميم عصري ببطانة داخلية.',
   (select id from cat where legacy_id = 'c1'), 1280.00, 0, 8,
   array['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600'],
   true, true, false, true, 4.7, 29, 0)
on conflict (legacy_id) do nothing;

with cat as (select legacy_id, id from public.categories)
insert into public.products (legacy_id, sku, name, short_description, description, category_id, price, old_price, stock, images, featured, is_new, on_sale, active, rating, reviews, display_order) values
  ('p11', 'BL-011', 'بلوزة حرير أنيقة', 'بلوزة حرير طبيعي',
   'بلوزة نسائية من الحرير الطبيعي، تصميم كلاسيكي مناسب للعمل والمناسبات.',
   (select id from cat where legacy_id = 'c2'), 340.00, 0, 18,
   array['https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=600'],
   false, true, false, true, 4.6, 35, 0)
on conflict (legacy_id) do nothing;

with cat as (select legacy_id, id from public.categories)
insert into public.products (legacy_id, sku, name, short_description, description, category_id, price, old_price, stock, images, featured, is_new, on_sale, active, rating, reviews, display_order) values
  ('p12', 'SH-012', 'حذاء كاجوال جلد', 'حذاء جلد طبيعي',
   'حذاء كاجوال رجالي من الجلد الطبيعي، نعل مريح للاستخدام اليومي الطويل.',
   (select id from cat where legacy_id = 'c3'), 540.00, 750.00, 14,
   array['https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=600'],
   false, false, true, true, 4.5, 44, 0)
on conflict (legacy_id) do nothing;

-- =========================================================
-- 4. product variants (seed uses legacy fields for the original variants)
-- =========================================================
-- p1 variants (size: S, M, L, XL)
with p as (select id from public.products where legacy_id = 'p1')
insert into public.product_variants (legacy_id, product_id, legacy_type, legacy_value, price, stock, active, display_order) values
  ('v1', (select id from p), 'size', 'S',  180.00,  6, true, 0),
  ('v2', (select id from p), 'size', 'M',  180.00,  8, true, 1),
  ('v3', (select id from p), 'size', 'L',  180.00,  6, true, 2),
  ('v4', (select id from p), 'size', 'XL', 180.00,  4, true, 3)
on conflict (legacy_id) do nothing;

-- p2 variants
with p as (select id from public.products where legacy_id = 'p2')
insert into public.product_variants (legacy_id, product_id, legacy_type, legacy_value, legacy_swatch, price, stock, active, display_order) values
  ('v5', (select id from p), 'size',  'S',     null, 850.00, 3, true, 0),
  ('v6', (select id from p), 'size',  'M',     null, 850.00, 4, true, 1),
  ('v7', (select id from p), 'size',  'L',     null, 850.00, 3, true, 2),
  ('v8', (select id from p), 'color', 'أسود',  '#000000', 850.00, 2, true, 3)
on conflict (legacy_id) do nothing;

-- p3 variants
with p as (select id from public.products where legacy_id = 'p3')
insert into public.product_variants (legacy_id, product_id, legacy_type, legacy_value, legacy_swatch, price, stock, active, display_order) values
  ('v9',  (select id from p), 'size',  '40',    null, 420.00, 4, true, 0),
  ('v10', (select id from p), 'size',  '41',    null, 420.00, 5, true, 1),
  ('v11', (select id from p), 'size',  '42',    null, 420.00, 5, true, 2),
  ('v12', (select id from p), 'size',  '43',    null, 420.00, 4, true, 3),
  ('v13', (select id from p), 'color', 'أبيض',  '#ffffff', 420.00, 0, true, 4)
on conflict (legacy_id) do nothing;

-- p6 variants
with p as (select id from public.products where legacy_id = 'p6')
insert into public.product_variants (legacy_id, product_id, legacy_type, legacy_value, legacy_swatch, price, stock, active, display_order) values
  ('v14', (select id from p), 'color', 'بني',  '#8B4513', 680.00, 5, true, 0),
  ('v15', (select id from p), 'color', 'أسود', '#000000', 680.00, 4, true, 1)
on conflict (legacy_id) do nothing;

-- p7 variants
with p as (select id from public.products where legacy_id = 'p7')
insert into public.product_variants (legacy_id, product_id, legacy_type, legacy_value, price, stock, active, display_order) values
  ('v16', (select id from p), 'size', '30', 220.00, 8,  true, 0),
  ('v17', (select id from p), 'size', '32', 220.00, 10, true, 1),
  ('v18', (select id from p), 'size', '34', 220.00, 9,  true, 2),
  ('v19', (select id from p), 'size', '36', 220.00, 8,  true, 3)
on conflict (legacy_id) do nothing;

-- p8 variants
with p as (select id from public.products where legacy_id = 'p8')
insert into public.product_variants (legacy_id, product_id, legacy_type, legacy_value, price, stock, active, display_order) values
  ('v20', (select id from p), 'size', 'S',  590.00, 4, true, 0),
  ('v21', (select id from p), 'size', 'M',  590.00, 4, true, 1),
  ('v22', (select id from p), 'size', 'L',  590.00, 4, true, 2),
  ('v23', (select id from p), 'size', 'XL', 590.00, 4, true, 3)
on conflict (legacy_id) do nothing;

-- p10 variants
with p as (select id from public.products where legacy_id = 'p10')
insert into public.product_variants (legacy_id, product_id, legacy_type, legacy_value, price, stock, active, display_order) values
  ('v24', (select id from p), 'size', 'M',  1280.00, 2, true, 0),
  ('v25', (select id from p), 'size', 'L',  1280.00, 3, true, 1),
  ('v26', (select id from p), 'size', 'XL', 1280.00, 3, true, 2)
on conflict (legacy_id) do nothing;

-- =========================================================
-- 5. coupons
-- =========================================================
insert into public.coupons (legacy_id, code, discount_type, value, min_order, max_uses, used, starts_at, expires_at, active) values
  ('co1', 'WELCOME10', 'percent', 10.00, 30.00, 100, 12, '2026-01-01T00:00:00Z', '2026-12-31T23:59:59Z', true),
  ('co2', 'SAVE5',     'fixed',    5.00, 50.00,  50,  8, '2026-01-01T00:00:00Z', '2026-09-30T23:59:59Z', true),
  ('co3', 'FREESHIP',  'fixed',    3.00,  0.00, 999, 45, '2026-01-01T00:00:00Z', '2026-12-31T23:59:59Z', true)
on conflict (legacy_id) do nothing;

-- =========================================================
-- 6. delivery areas (Jordanian governorates)
-- =========================================================
insert into public.delivery_areas (legacy_id, name, shipping_cost, active, display_order) values
  ('d1',  'عمّان',   2.00, true,  1),
  ('d2',  'إربد',   4.00, true,  2),
  ('d3',  'الزرقاء', 3.00, true,  3),
  ('d4',  'العقبة', 5.00, true,  4),
  ('d5',  'البلقاء', 3.00, true,  5),
  ('d6',  'المفرق', 5.00, true,  6),
  ('d7',  'جرش',   4.00, true,  7),
  ('d8',  'عجلون', 4.00, true,  8),
  ('d9',  'الكرك', 5.00, true,  9),
  ('d10', 'معان',  6.00, true, 10),
  ('d11', 'الطفيلة',6.00, true, 11),
  ('d12', 'مادبا', 3.00, true, 12)
on conflict (legacy_id) do nothing;
